version: 2
jobs:
  build:
    docker:
      - image: seike460/gridsome-aws:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: apk add --no-cache --virtual .build-deps make gcc g++ python
      - run: yarn global add npm
      - run: npm install --production --silent
      - run: apk del .build-deps
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run build
      #- run: yarn test
